language: node_js

node_js:
  - "0.10"
  - "4.2"

services:
  - riak

# before_install:
#   - "sudo apt-get purge riak"
#   - "curl -sO http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.0beta1/ubuntu/precise/riak_2.0.0beta1-1_amd64.deb"
#   - "sudo dpkg -i riak_2.0.0beta1-1_amd64.deb"
#   - "sudo service riak start"
#   - "sleep 10"
